### ISSUE TITLE
DateTimePicker large font/language text cut off

### ISSUE THREAD

**Issue by sigute** [OfficeDev/ui-fabric-android#10]
When using a device setting to increase the font size, in date picker time selection tab, the dates are getting cut off in the following scenarios.

- Largest font size is set, date for the next year selected (English)
- For some languages, formatted date is very long and issue occurs with default font size as well when selecting a date for next year (Portuguese used for testing here)
- Affects both, portrait and landscape, tested on Pixel 3, API 29. 

We could adjust the padding to partially resolve this. For long language combined with big text, just padding will not cover it, so might need to remove some date information when time tab is selected, potentially day of the week or year? And as another approach, text could autosize down to fit into the available width (but this could create accessibility problem if it is not big enough for user to see after autosizing down). 

Screenshots:
![Screenshot_1585561270](https://user-images.githubusercontent.com/5782728/77899408-f0d19680-727c-11ea-956f-9c39504900c5.png)
![Screenshot_1585561275](https://user-images.githubusercontent.com/5782728/77899412-f29b5a00-727c-11ea-8eb5-bc1869262253.png)
![Screenshot_1585561617](https://user-images.githubusercontent.com/5782728/77899415-f4651d80-727c-11ea-950f-7b9c10df0c4a.png)

**Comment by lynamemi** [comment]
Hey @sigute thanks for reporting!  The new fabric-android owner is in the process of onboarding so when he gets set up I'll make sure you two connect. Feel free to ping us on Teams and I can connect you there as well.

**Comment by lynamemi** [comment]
This repo is getting archived and has moved to: https://github.com/microsoft/fluentui-android instead.
