### ISSUE TITLE
Issue in RTL in Date Time Picker

### ISSUE THREAD

**Issue by anmit14** [OfficeDev/ui-fabric-android#11]
The hours and minutes appear in reverse.

Please refer the attached screenshot.

![RTL](https://user-images.githubusercontent.com/63837157/79538030-2362f800-80a1-11ea-912c-411419ce9017.jpeg)

**Comment by lynamemi** [comment]
This repo is getting archived and has moved to: https://github.com/microsoft/fluentui-android instead.
