### ISSUE TITLE
Bitmap support for BottomSheetItem

### ISSUE THREAD

**Issue by AlexKutschera** [OfficeDev/ui-fabric-android#12]
For my project I need to be able to provide bitmaps instead of android resource ids to the BottomSheetItem. I Implemented the functionality and tested around with it for a bit and would like to contribute my code changes. What do I have to do?

**Comment by aishwarya56** [comment]
Hey, thanks a lot for your support and the intent to contribute to the Repo.
I would request you to raise your Pull request on our new Github Repo which is [here](https://github.com/microsoft/fluentui-android) 
We are currently in the process of migrating everything from Fabric to Fluent.

**Comment by AlexKutschera** [comment]
I can't push into a new branch for the new Repo, it says the permission was denied. Do I need an invite or am I doing something wrong?

**Comment by lynamemi** [comment]
This repo is getting archived and has moved to: https://github.com/microsoft/fluentui-android instead.
