### ISSUE TITLE
DateTimePicker landscape width

### ISSUE THREAD

**Issue by sigute** [OfficeDev/ui-fabric-android#7]
Date picker in landscape mode on a phone is very wide, compared to portrait width or to tablet implementation. Could the width be adjusted to be less wide and to make more days visible?

![Screenshot_1578647490](https://user-images.githubusercontent.com/5782728/72140740-b8af6b80-3391-11ea-99f8-e1e84e32fa8f.png)
![Screenshot_1578647548](https://user-images.githubusercontent.com/5782728/72140742-b8af6b80-3391-11ea-916f-fbb04df907a7.png)

**Comment by williamado** [comment]
The landscape design was adopted from the original source designs. If you are wanting to implement changes to the landscape design, I would suggest raising an issue with the Toolkit owners. Feel free to follow up offline if you have more questions.

**Comment by lynamemi** [comment]
This repo is getting archived and has moved to: https://github.com/microsoft/fluentui-android instead.
