### ISSUE TITLE
CalendarView day name in Russian

### ISSUE THREAD

**Issue by aconsuegra** [OfficeDev/ui-fabric-android#8]
Right now, the CalendarView is using only one letter as week day name in most (if not all) languages, including Russian.

According to our translators, having only one letter for week days makes no sense in Russian (same for Ukrainian and Belorussians) so the library should be using the 2 letters form, like seen in this screenshot:

![Screenshot_1580214604](https://user-images.githubusercontent.com/1814882/73266034-5f8b6880-41d6-11ea-91af-69538476a1f1.png)

**Comment by lynamemi** [comment]
Thanks for reporting! We work with Touchdown Build service to get our translations - I sent a message to their support team to see what the best way is to go about getting these fixed.

I'll keep you posted.

**Comment by lynamemi** [comment]
@aconsuegra I added more comments to our initial strings + altered the TDBuild contact so hopefully we'll get some traction for this.

**Comment by lynamemi** [comment]
@aconsuegra The globalization partner team got these strings updated for us in Russian and Ukrainian. I've included that update in a new version: [0.3.8](https://github.com/OfficeDev/ui-fabric-android/releases/tag/0.3.8)

**Comment by aconsuegra** [comment]
Thanks!
