### ISSUE TITLE
Option to set first of week in CalendarView

### ISSUE THREAD

**Issue by aconsuegra** [OfficeDev/ui-fabric-android#9]
Hi,

We are trying to change the first day of week for the CalendarView, to use either the device system setting or a local setting. We have seen in the repo a PreferenceManager with a function to retrieve the first day of the week stored in shared preferences, but we can't find an exposed way of modifying those preferences. Are we missing anything? Could you point us to the documentation about how to use this PreferenceManager?

Thanks!

**Comment by williamado** [comment]
There isn't a way to change this at the moment; however, feel free to contribute this functionality with a Pull Request and we'll review it as soon as possible.

**Comment by vladfilyakov** [comment]
@aconsuegra Since you are Microsoft employee please follow the guidelines for internal contributions (on ADO).

**Comment by aconsuegra** [comment]
@vladfilyakov Cool, I'll do that, thanks!
